string sorting
js-tasks-ru/js-20220909_aleksandra-bondar pull request #2
Opened 2022-09-13 20:39 UTC by devisable

2022-09-13 20:40 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-13 21:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-13 21:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-14 16:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-14 16:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-15 22:32 UTC, dosandk commented on 01-intro/1-sum/index.js
> +	return m + n;
👍 good

2022-09-15 22:47 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let arrCopy = arr.slice();
`const arrCopy = [...arr]` - более современный способ скопировать массив

2022-09-15 22:47 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param === 'desc' ? arrCopy.reverse() : arrCopy;
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-15 22:47 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let pickObj = {};
`const`

2022-09-15 22:48 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    return pickObj;
какой результат будет при вызове 
```
pick({}, 'constructor')
```
Почему?

2022-09-15 22:48 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let omitObj = {};
`const omitObj`

2022-09-15 22:48 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let key of Object.keys(obj)) {
`const key`

2022-09-15 22:48 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-16 09:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-17 18:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    } else {
было бы неплохо явно указать `if (param === 'asc')`

2022-09-17 18:17 UTC, dosandk approved these changes
good 👍

2022-09-17 18:17 UTC, merged